ARG PYTHON_BASE_IMAGE=python:3.11.0-slim
# any python image with poetry installed
ARG BUILDER_BASE_IMAGE=omelet034/python-3.11.0-slim-poetry:latest
# This dockerfile builds a image for testing purposes and run all tests using the image

FROM ${BUILDER_BASE_IMAGE} as builder
COPY ./poetry.lock ./pyproject.toml /app_root/
WORKDIR /app_root
RUN poetry install --no-interaction --no-root

FROM ${PYTHON_BASE_IMAGE} as test-image
WORKDIR /app_root
COPY ./poetry.lock ./pyproject.toml /app_root/
COPY --from=builder /app_root/.venv /app_root/.venv
COPY ./scripts/test.sh /app_server/test.sh
COPY /app /app_root/app/
COPY /tests /app_root/tests/
RUN chmod +x /app_server/test.sh
CMD ["/app_server/test.sh", "/app_root/tests", "--cov=app", "--cov-report=term-missing"]
