version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  app:
    image: omelet034/thumbnail-app:latest
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  worker:
    image: omelet034/thumbnail-app-worker:latest
    depends_on:
      - redis
      - mongo
