---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-fs
  name: simple-fs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-fs
  strategy: {}
  template:
    metadata:
      labels:
        app: simple-fs
    spec:
      containers:
      - image: omelet034/simple-fs:latest
        name: simple-fs
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 2
          timeoutSeconds: 3
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          timeoutSeconds: 3
          periodSeconds: 3
        volumeMounts:
        - mountPath: /data
          name: simplefs-data
        resources: 
          requests:
            memory: "1024Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "550m"
      restartPolicy: Always
      volumes:
      - name: simplefs-data
        persistentVolumeClaim:
          claimName: cephfs-pvc
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-fs
  name: simple-fs
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30010
  selector:
    app: simple-fs